# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cilia_gui_384.ui'
#
# Created: Mon Aug  3 20:38:26 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CiliaC(object):
    def setupUi(self, CiliaC):
        CiliaC.setObjectName(_fromUtf8("CiliaC"))
        CiliaC.setEnabled(True)
        CiliaC.resize(1173, 666)
        CiliaC.setWindowTitle(_fromUtf8("CiliaC"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/images/summed.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CiliaC.setWindowIcon(icon)
        CiliaC.setAccessibleName(_fromUtf8("CiliaC"))
        self.centralwidget = QtGui.QWidget(CiliaC)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.view1GraphicsView = GraphicsView(self.centralwidget)
        self.view1GraphicsView.setGeometry(QtCore.QRect(316, 33, 384, 384))
        self.view1GraphicsView.setMinimumSize(QtCore.QSize(0, 255))
        self.view1GraphicsView.setMouseTracking(False)
        self.view1GraphicsView.setObjectName(_fromUtf8("view1GraphicsView"))
        self.buttonRedraw = QtGui.QToolButton(self.centralwidget)
        self.buttonRedraw.setGeometry(QtCore.QRect(1015, 424, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRedraw.setIcon(icon1)
        self.buttonRedraw.setObjectName(_fromUtf8("buttonRedraw"))
        self.buttonPrevImage = QtGui.QPushButton(self.centralwidget)
        self.buttonPrevImage.setGeometry(QtCore.QRect(591, 430, 31, 24))
        self.buttonPrevImage.setObjectName(_fromUtf8("buttonPrevImage"))
        self.buttonNextImage = QtGui.QPushButton(self.centralwidget)
        self.buttonNextImage.setGeometry(QtCore.QRect(806, 430, 31, 24))
        self.buttonNextImage.setObjectName(_fromUtf8("buttonNextImage"))
        self.buttonAnimateStart = QtGui.QToolButton(self.centralwidget)
        self.buttonAnimateStart.setGeometry(QtCore.QRect(696, 446, 41, 31))
        self.buttonAnimateStart.setStatusTip(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAnimateStart.setIcon(icon2)
        self.buttonAnimateStart.setCheckable(True)
        self.buttonAnimateStart.setObjectName(_fromUtf8("buttonAnimateStart"))
        self.imageSlider = QtGui.QSlider(self.centralwidget)
        self.imageSlider.setGeometry(QtCore.QRect(625, 430, 171, 23))
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setObjectName(_fromUtf8("imageSlider"))
        self.buttonRotateLeft = QtGui.QToolButton(self.centralwidget)
        self.buttonRotateLeft.setGeometry(QtCore.QRect(935, 424, 31, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/object-rotate-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateLeft.setIcon(icon3)
        self.buttonRotateLeft.setObjectName(_fromUtf8("buttonRotateLeft"))
        self.buttonRotateRight = QtGui.QToolButton(self.centralwidget)
        self.buttonRotateRight.setGeometry(QtCore.QRect(970, 424, 31, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/object-rotate-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateRight.setIcon(icon4)
        self.buttonRotateRight.setObjectName(_fromUtf8("buttonRotateRight"))
        self.buttonSmooth = QtGui.QToolButton(self.centralwidget)
        self.buttonSmooth.setGeometry(QtCore.QRect(70, 112, 31, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/view-object-histogram-logarithmic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSmooth.setIcon(icon5)
        self.buttonSmooth.setObjectName(_fromUtf8("buttonSmooth"))
        self.buttonLoadFile = QtGui.QToolButton(self.centralwidget)
        self.buttonLoadFile.setGeometry(QtCore.QRect(20, 40, 31, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/document-open-data.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadFile.setIcon(icon6)
        self.buttonLoadFile.setObjectName(_fromUtf8("buttonLoadFile"))
        self.buttonExit = QtGui.QToolButton(self.centralwidget)
        self.buttonExit.setGeometry(QtCore.QRect(1120, 550, 51, 51))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonExit.setIcon(icon7)
        self.buttonExit.setIconSize(QtCore.QSize(32, 32))
        self.buttonExit.setObjectName(_fromUtf8("buttonExit"))
        self.buttonCentreOfMass = QtGui.QPushButton(self.centralwidget)
        self.buttonCentreOfMass.setGeometry(QtCore.QRect(100, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonCentreOfMass.setFont(font)
        self.buttonCentreOfMass.setObjectName(_fromUtf8("buttonCentreOfMass"))
        self.buttonSummedImage = QtGui.QToolButton(self.centralwidget)
        self.buttonSummedImage.setGeometry(QtCore.QRect(20, 112, 31, 31))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/summed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSummedImage.setIcon(icon8)
        self.buttonSummedImage.setCheckable(True)
        self.buttonSummedImage.setObjectName(_fromUtf8("buttonSummedImage"))
        self.progressLog = QtGui.QTextEdit(self.centralwidget)
        self.progressLog.setGeometry(QtCore.QRect(310, 484, 516, 121))
        self.progressLog.setObjectName(_fromUtf8("progressLog"))
        self.buttonRender = QtGui.QToolButton(self.centralwidget)
        self.buttonRender.setGeometry(QtCore.QRect(20, 148, 31, 31))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/ssurf-plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRender.setIcon(icon9)
        self.buttonRender.setCheckable(True)
        self.buttonRender.setObjectName(_fromUtf8("buttonRender"))
        self.buttonVHPlot = QtGui.QToolButton(self.centralwidget)
        self.buttonVHPlot.setGeometry(QtCore.QRect(70, 148, 31, 31))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("images/combined_graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonVHPlot.setIcon(icon10)
        self.buttonVHPlot.setCheckable(False)
        self.buttonVHPlot.setObjectName(_fromUtf8("buttonVHPlot"))
        self.groupBoxUnits = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxUnits.setGeometry(QtCore.QRect(150, 80, 131, 71))
        self.groupBoxUnits.setFlat(False)
        self.groupBoxUnits.setObjectName(_fromUtf8("groupBoxUnits"))
        self.radioButtonFrames = QtGui.QRadioButton(self.groupBoxUnits)
        self.radioButtonFrames.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.radioButtonFrames.setChecked(False)
        self.radioButtonFrames.setObjectName(_fromUtf8("radioButtonFrames"))
        self.radioButtonTime = QtGui.QRadioButton(self.groupBoxUnits)
        self.radioButtonTime.setGeometry(QtCore.QRect(10, 40, 97, 21))
        self.radioButtonTime.setChecked(True)
        self.radioButtonTime.setObjectName(_fromUtf8("radioButtonTime"))
        self.buttonShowOverlays = QtGui.QCheckBox(self.centralwidget)
        self.buttonShowOverlays.setGeometry(QtCore.QRect(335, 440, 131, 21))
        self.buttonShowOverlays.setChecked(True)
        self.buttonShowOverlays.setObjectName(_fromUtf8("buttonShowOverlays"))
        self.view2GraphicsView = GraphicsView(self.centralwidget)
        self.view2GraphicsView.setGeometry(QtCore.QRect(750, 33, 384, 384))
        self.view2GraphicsView.setMouseTracking(False)
        self.view2GraphicsView.setObjectName(_fromUtf8("view2GraphicsView"))
        self.spinFrom = QtGui.QSpinBox(self.centralwidget)
        self.spinFrom.setGeometry(QtCore.QRect(200, 242, 52, 31))
        self.spinFrom.setObjectName(_fromUtf8("spinFrom"))
        self.labelFrom = QtGui.QLabel(self.centralwidget)
        self.labelFrom.setGeometry(QtCore.QRect(155, 250, 41, 16))
        self.labelFrom.setObjectName(_fromUtf8("labelFrom"))
        self.labelTo = QtGui.QLabel(self.centralwidget)
        self.labelTo.setGeometry(QtCore.QRect(170, 290, 21, 16))
        self.labelTo.setObjectName(_fromUtf8("labelTo"))
        self.spinTo = QtGui.QSpinBox(self.centralwidget)
        self.spinTo.setGeometry(QtCore.QRect(200, 280, 52, 31))
        self.spinTo.setMaximum(999)
        self.spinTo.setObjectName(_fromUtf8("spinTo"))
        self.view1Title = QtGui.QLabel(self.centralwidget)
        self.view1Title.setGeometry(QtCore.QRect(420, 10, 151, 20))
        self.view1Title.setText(_fromUtf8(""))
        self.view1Title.setObjectName(_fromUtf8("view1Title"))
        self.view2Title = QtGui.QLabel(self.centralwidget)
        self.view2Title.setGeometry(QtCore.QRect(860, 10, 151, 20))
        self.view2Title.setText(_fromUtf8(""))
        self.view2Title.setObjectName(_fromUtf8("view2Title"))
        self.groupBoxCOM = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCOM.setGeometry(QtCore.QRect(-1, 240, 141, 91))
        self.groupBoxCOM.setTitle(_fromUtf8(""))
        self.groupBoxCOM.setObjectName(_fromUtf8("groupBoxCOM"))
        self.radioCOMFrame = QtGui.QRadioButton(self.groupBoxCOM)
        self.radioCOMFrame.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioCOMFrame.setFont(font)
        self.radioCOMFrame.setChecked(True)
        self.radioCOMFrame.setObjectName(_fromUtf8("radioCOMFrame"))
        self.radioCOMInside = QtGui.QRadioButton(self.groupBoxCOM)
        self.radioCOMInside.setGeometry(QtCore.QRect(10, 32, 97, 21))
        self.radioCOMInside.setObjectName(_fromUtf8("radioCOMInside"))
        self.radioCOMPeak = QtGui.QRadioButton(self.groupBoxCOM)
        self.radioCOMPeak.setGeometry(QtCore.QRect(10, 56, 111, 21))
        self.radioCOMPeak.setObjectName(_fromUtf8("radioCOMPeak"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.labelFrameNumber = QtGui.QLabel(self.centralwidget)
        self.labelFrameNumber.setGeometry(QtCore.QRect(705, 372, 41, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelFrameNumber.setFont(font)
        self.labelFrameNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrameNumber.setObjectName(_fromUtf8("labelFrameNumber"))
        self.buttonCalcVelocity = QtGui.QPushButton(self.centralwidget)
        self.buttonCalcVelocity.setGeometry(QtCore.QRect(210, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.buttonCalcVelocity.setFont(font)
        self.buttonCalcVelocity.setObjectName(_fromUtf8("buttonCalcVelocity"))
        self.buttonProcessProceed = QtGui.QPushButton(self.centralwidget)
        self.buttonProcessProceed.setEnabled(False)
        self.buttonProcessProceed.setGeometry(QtCore.QRect(145, 396, 94, 77))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 255, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 223, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 223, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 255, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 223, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 223, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 255, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 223, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.buttonProcessProceed.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.buttonProcessProceed.setFont(font)
        self.buttonProcessProceed.setAutoFillBackground(False)
        self.buttonProcessProceed.setObjectName(_fromUtf8("buttonProcessProceed"))
        self.buttonProcessCancel = QtGui.QPushButton(self.centralwidget)
        self.buttonProcessCancel.setEnabled(False)
        self.buttonProcessCancel.setGeometry(QtCore.QRect(45, 396, 94, 77))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.buttonProcessCancel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.buttonProcessCancel.setFont(font)
        self.buttonProcessCancel.setAutoFillBackground(False)
        self.buttonProcessCancel.setObjectName(_fromUtf8("buttonProcessCancel"))
        self.buttonSaveFile = QtGui.QToolButton(self.centralwidget)
        self.buttonSaveFile.setGeometry(QtCore.QRect(70, 40, 31, 31))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("images/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSaveFile.setIcon(icon11)
        self.buttonSaveFile.setObjectName(_fromUtf8("buttonSaveFile"))
        self.buttonSaveReport = QtGui.QToolButton(self.centralwidget)
        self.buttonSaveReport.setGeometry(QtCore.QRect(20, 72, 31, 31))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("images/acrobat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSaveReport.setIcon(icon12)
        self.buttonSaveReport.setObjectName(_fromUtf8("buttonSaveReport"))
        self.buttonSaveAsCSV = QtGui.QToolButton(self.centralwidget)
        self.buttonSaveAsCSV.setGeometry(QtCore.QRect(70, 72, 31, 31))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("images/excel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSaveAsCSV.setIcon(icon13)
        self.buttonSaveAsCSV.setObjectName(_fromUtf8("buttonSaveAsCSV"))
        self.view1SliderMin = QtGui.QSlider(self.centralwidget)
        self.view1SliderMin.setGeometry(QtCore.QRect(700, 116, 23, 160))
        self.view1SliderMin.setMaximum(1024)
        self.view1SliderMin.setProperty("value", 0)
        self.view1SliderMin.setSliderPosition(0)
        self.view1SliderMin.setOrientation(QtCore.Qt.Vertical)
        self.view1SliderMin.setObjectName(_fromUtf8("view1SliderMin"))
        self.view1SliderMax = QtGui.QSlider(self.centralwidget)
        self.view1SliderMax.setGeometry(QtCore.QRect(715, 116, 23, 160))
        self.view1SliderMax.setMinimum(1)
        self.view1SliderMax.setMaximum(512)
        self.view1SliderMax.setProperty("value", 512)
        self.view1SliderMax.setSliderPosition(512)
        self.view1SliderMax.setOrientation(QtCore.Qt.Vertical)
        self.view1SliderMax.setObjectName(_fromUtf8("view1SliderMax"))
        self.view2SliderMin = QtGui.QSlider(self.centralwidget)
        self.view2SliderMin.setGeometry(QtCore.QRect(1135, 120, 23, 160))
        self.view2SliderMin.setMaximum(1024)
        self.view2SliderMin.setOrientation(QtCore.Qt.Vertical)
        self.view2SliderMin.setObjectName(_fromUtf8("view2SliderMin"))
        self.view2SliderMax = QtGui.QSlider(self.centralwidget)
        self.view2SliderMax.setGeometry(QtCore.QRect(1150, 120, 23, 160))
        self.view2SliderMax.setMinimum(1)
        self.view2SliderMax.setMaximum(512)
        self.view2SliderMax.setProperty("value", 512)
        self.view2SliderMax.setSliderPosition(512)
        self.view2SliderMax.setOrientation(QtCore.Qt.Vertical)
        self.view2SliderMax.setObjectName(_fromUtf8("view2SliderMax"))
        self.view1BCAutoCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.view1BCAutoCheckbox.setGeometry(QtCore.QRect(710, 88, 26, 21))
        self.view1BCAutoCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.view1BCAutoCheckbox.setText(_fromUtf8(""))
        self.view1BCAutoCheckbox.setChecked(True)
        self.view1BCAutoCheckbox.setObjectName(_fromUtf8("view1BCAutoCheckbox"))
        self.view1BCAutoLabel = QtGui.QLabel(self.centralwidget)
        self.view1BCAutoLabel.setGeometry(QtCore.QRect(705, 70, 41, 16))
        self.view1BCAutoLabel.setObjectName(_fromUtf8("view1BCAutoLabel"))
        self.view2BCAutoLabel = QtGui.QLabel(self.centralwidget)
        self.view2BCAutoLabel.setGeometry(QtCore.QRect(1135, 70, 41, 16))
        self.view2BCAutoLabel.setObjectName(_fromUtf8("view2BCAutoLabel"))
        self.view2BCAutoCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.view2BCAutoCheckbox.setGeometry(QtCore.QRect(1140, 88, 26, 21))
        self.view2BCAutoCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.view2BCAutoCheckbox.setText(_fromUtf8(""))
        self.view2BCAutoCheckbox.setChecked(True)
        self.view2BCAutoCheckbox.setObjectName(_fromUtf8("view2BCAutoCheckbox"))
        self.animDelaySlider = QtGui.QSlider(self.centralwidget)
        self.animDelaySlider.setEnabled(True)
        self.animDelaySlider.setGeometry(QtCore.QRect(39, 488, 196, 23))
        self.animDelaySlider.setMinimum(10)
        self.animDelaySlider.setMaximum(750)
        self.animDelaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.animDelaySlider.setObjectName(_fromUtf8("animDelaySlider"))
        CiliaC.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CiliaC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuCreate_Report = QtGui.QMenu(self.menu_File)
        self.menuCreate_Report.setObjectName(_fromUtf8("menuCreate_Report"))
        self.menu_Image = QtGui.QMenu(self.menubar)
        self.menu_Image.setObjectName(_fromUtf8("menu_Image"))
        self.menuRotate = QtGui.QMenu(self.menu_Image)
        self.menuRotate.setObjectName(_fromUtf8("menuRotate"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        self.menuPrint = QtGui.QMenu(self.menuPlot)
        self.menuPrint.setObjectName(_fromUtf8("menuPrint"))
        self.menuMeasure = QtGui.QMenu(self.menubar)
        self.menuMeasure.setObjectName(_fromUtf8("menuMeasure"))
        self.menuTrack = QtGui.QMenu(self.menubar)
        self.menuTrack.setObjectName(_fromUtf8("menuTrack"))
        self.menuMask = QtGui.QMenu(self.menuTrack)
        self.menuMask.setObjectName(_fromUtf8("menuMask"))
        self.menuISO = QtGui.QMenu(self.menuTrack)
        self.menuISO.setObjectName(_fromUtf8("menuISO"))
        self.menuTrack_Manual = QtGui.QMenu(self.menuTrack)
        self.menuTrack_Manual.setObjectName(_fromUtf8("menuTrack_Manual"))
        self.menuTrack_Movement = QtGui.QMenu(self.menuTrack_Manual)
        self.menuTrack_Movement.setObjectName(_fromUtf8("menuTrack_Movement"))
        self.menuTrack_Spiral = QtGui.QMenu(self.menuTrack_Manual)
        self.menuTrack_Spiral.setObjectName(_fromUtf8("menuTrack_Spiral"))
        self.menuTrack_Auto = QtGui.QMenu(self.menuTrack)
        self.menuTrack_Auto.setObjectName(_fromUtf8("menuTrack_Auto"))
        self.menuTrack_No_ROI = QtGui.QMenu(self.menuTrack_Auto)
        self.menuTrack_No_ROI.setObjectName(_fromUtf8("menuTrack_No_ROI"))
        self.menuTrack_Fixed_ROI = QtGui.QMenu(self.menuTrack_Auto)
        self.menuTrack_Fixed_ROI.setObjectName(_fromUtf8("menuTrack_Fixed_ROI"))
        self.menuTrack_Moving_ROI = QtGui.QMenu(self.menuTrack_Auto)
        self.menuTrack_Moving_ROI.setObjectName(_fromUtf8("menuTrack_Moving_ROI"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSet = QtGui.QMenu(self.menubar)
        self.menuSet.setObjectName(_fromUtf8("menuSet"))
        self.menuTracking = QtGui.QMenu(self.menuSet)
        self.menuTracking.setObjectName(_fromUtf8("menuTracking"))
        self.menu3D_Plot = QtGui.QMenu(self.menuSet)
        self.menu3D_Plot.setObjectName(_fromUtf8("menu3D_Plot"))
        self.menuLog_Level = QtGui.QMenu(self.menuSet)
        self.menuLog_Level.setObjectName(_fromUtf8("menuLog_Level"))
        self.menuManual = QtGui.QMenu(self.menubar)
        self.menuManual.setObjectName(_fromUtf8("menuManual"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        CiliaC.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CiliaC)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CiliaC.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(CiliaC)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDICOM_Info = QtGui.QAction(CiliaC)
        self.actionDICOM_Info.setObjectName(_fromUtf8("actionDICOM_Info"))
        self.actionRotate_L = QtGui.QAction(CiliaC)
        self.actionRotate_L.setObjectName(_fromUtf8("actionRotate_L"))
        self.actionRotate_R = QtGui.QAction(CiliaC)
        self.actionRotate_R.setObjectName(_fromUtf8("actionRotate_R"))
        self.actionSmooth = QtGui.QAction(CiliaC)
        self.actionSmooth.setObjectName(_fromUtf8("actionSmooth"))
        self.action3D_Mesh = QtGui.QAction(CiliaC)
        self.action3D_Mesh.setObjectName(_fromUtf8("action3D_Mesh"))
        self.actionXYPlots = QtGui.QAction(CiliaC)
        self.actionXYPlots.setObjectName(_fromUtf8("actionXYPlots"))
        self.actionInside_ROI = QtGui.QAction(CiliaC)
        self.actionInside_ROI.setCheckable(True)
        self.actionInside_ROI.setObjectName(_fromUtf8("actionInside_ROI"))
        self.actionROI_Peak = QtGui.QAction(CiliaC)
        self.actionROI_Peak.setCheckable(True)
        self.actionROI_Peak.setObjectName(_fromUtf8("actionROI_Peak"))
        self.actionScale = QtGui.QAction(CiliaC)
        self.actionScale.setObjectName(_fromUtf8("actionScale"))
        self.actionReload_data = QtGui.QAction(CiliaC)
        self.actionReload_data.setObjectName(_fromUtf8("actionReload_data"))
        self.actionRemove_Background = QtGui.QAction(CiliaC)
        self.actionRemove_Background.setObjectName(_fromUtf8("actionRemove_Background"))
        self.actionChange_Units = QtGui.QAction(CiliaC)
        self.actionChange_Units.setObjectName(_fromUtf8("actionChange_Units"))
        self.actionPrint_Virt = QtGui.QAction(CiliaC)
        self.actionPrint_Virt.setObjectName(_fromUtf8("actionPrint_Virt"))
        self.actionPrint_Horiz = QtGui.QAction(CiliaC)
        self.actionPrint_Horiz.setObjectName(_fromUtf8("actionPrint_Horiz"))
        self.actionFit_Line = QtGui.QAction(CiliaC)
        self.actionFit_Line.setObjectName(_fromUtf8("actionFit_Line"))
        self.actionStraighten = QtGui.QAction(CiliaC)
        self.actionStraighten.setObjectName(_fromUtf8("actionStraighten"))
        self.actionExport = QtGui.QAction(CiliaC)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionVelocity_Limits = QtGui.QAction(CiliaC)
        self.actionVelocity_Limits.setObjectName(_fromUtf8("actionVelocity_Limits"))
        self.actionCalcVelocity = QtGui.QAction(CiliaC)
        self.actionCalcVelocity.setObjectName(_fromUtf8("actionCalcVelocity"))
        self.actionHelpAbout = QtGui.QAction(CiliaC)
        self.actionHelpAbout.setObjectName(_fromUtf8("actionHelpAbout"))
        self.actionMask_Frames = QtGui.QAction(CiliaC)
        self.actionMask_Frames.setObjectName(_fromUtf8("actionMask_Frames"))
        self.actionAdd_Mask = QtGui.QAction(CiliaC)
        self.actionAdd_Mask.setObjectName(_fromUtf8("actionAdd_Mask"))
        self.actionApply_Mask = QtGui.QAction(CiliaC)
        self.actionApply_Mask.setObjectName(_fromUtf8("actionApply_Mask"))
        self.actionRemove_Mask = QtGui.QAction(CiliaC)
        self.actionRemove_Mask.setObjectName(_fromUtf8("actionRemove_Mask"))
        self.actionAdd_ROI = QtGui.QAction(CiliaC)
        self.actionAdd_ROI.setObjectName(_fromUtf8("actionAdd_ROI"))
        self.actionDelete_ROI = QtGui.QAction(CiliaC)
        self.actionDelete_ROI.setObjectName(_fromUtf8("actionDelete_ROI"))
        self.actionEntire_Frame = QtGui.QAction(CiliaC)
        self.actionEntire_Frame.setCheckable(True)
        self.actionEntire_Frame.setChecked(True)
        self.actionEntire_Frame.setObjectName(_fromUtf8("actionEntire_Frame"))
        self.actionReset_Limits = QtGui.QAction(CiliaC)
        self.actionReset_Limits.setObjectName(_fromUtf8("actionReset_Limits"))
        self.actionSummary = QtGui.QAction(CiliaC)
        self.actionSummary.setObjectName(_fromUtf8("actionSummary"))
        self.actionLateral_Movement = QtGui.QAction(CiliaC)
        self.actionLateral_Movement.setObjectName(_fromUtf8("actionLateral_Movement"))
        self.actionVirtical_Movement_2 = QtGui.QAction(CiliaC)
        self.actionVirtical_Movement_2.setObjectName(_fromUtf8("actionVirtical_Movement_2"))
        self.actionPlot_Size = QtGui.QAction(CiliaC)
        self.actionPlot_Size.setObjectName(_fromUtf8("actionPlot_Size"))
        self.actionSet_Animation_Speed = QtGui.QAction(CiliaC)
        self.actionSet_Animation_Speed.setCheckable(True)
        self.actionSet_Animation_Speed.setObjectName(_fromUtf8("actionSet_Animation_Speed"))
        self.actionAnalyse_Calibration_Image = QtGui.QAction(CiliaC)
        self.actionAnalyse_Calibration_Image.setObjectName(_fromUtf8("actionAnalyse_Calibration_Image"))
        self.actionTrackThreshold = QtGui.QAction(CiliaC)
        self.actionTrackThreshold.setObjectName(_fromUtf8("actionTrackThreshold"))
        self.actionTrackBins = QtGui.QAction(CiliaC)
        self.actionTrackBins.setObjectName(_fromUtf8("actionTrackBins"))
        self.action3dZ_scale = QtGui.QAction(CiliaC)
        self.action3dZ_scale.setObjectName(_fromUtf8("action3dZ_scale"))
        self.actionLoad_Dicom_File = QtGui.QAction(CiliaC)
        self.actionLoad_Dicom_File.setObjectName(_fromUtf8("actionLoad_Dicom_File"))
        self.actionSave_Dicom_File = QtGui.QAction(CiliaC)
        self.actionSave_Dicom_File.setObjectName(_fromUtf8("actionSave_Dicom_File"))
        self.actionRotate_Lat = QtGui.QAction(CiliaC)
        self.actionRotate_Lat.setObjectName(_fromUtf8("actionRotate_Lat"))
        self.actionRotate_Using_ROI = QtGui.QAction(CiliaC)
        self.actionRotate_Using_ROI.setObjectName(_fromUtf8("actionRotate_Using_ROI"))
        self.actionRotate_90_Deg_Left = QtGui.QAction(CiliaC)
        self.actionRotate_90_Deg_Left.setObjectName(_fromUtf8("actionRotate_90_Deg_Left"))
        self.actionRotate_90_Deg_Right = QtGui.QAction(CiliaC)
        self.actionRotate_90_Deg_Right.setObjectName(_fromUtf8("actionRotate_90_Deg_Right"))
        self.actionRotate_Set_Lateral_Angle = QtGui.QAction(CiliaC)
        self.actionRotate_Set_Lateral_Angle.setObjectName(_fromUtf8("actionRotate_Set_Lateral_Angle"))
        self.actionSet_Summed_Sensitivity = QtGui.QAction(CiliaC)
        self.actionSet_Summed_Sensitivity.setObjectName(_fromUtf8("actionSet_Summed_Sensitivity"))
        self.actionSet_Preprocess_image_on_Load = QtGui.QAction(CiliaC)
        self.actionSet_Preprocess_image_on_Load.setCheckable(True)
        self.actionSet_Preprocess_image_on_Load.setChecked(True)
        self.actionSet_Preprocess_image_on_Load.setObjectName(_fromUtf8("actionSet_Preprocess_image_on_Load"))
        self.actionMeasure_Size_Inside_ROI = QtGui.QAction(CiliaC)
        self.actionMeasure_Size_Inside_ROI.setObjectName(_fromUtf8("actionMeasure_Size_Inside_ROI"))
        self.actionSetLogInfo = QtGui.QAction(CiliaC)
        self.actionSetLogInfo.setCheckable(False)
        self.actionSetLogInfo.setObjectName(_fromUtf8("actionSetLogInfo"))
        self.actionSetLogWarning = QtGui.QAction(CiliaC)
        self.actionSetLogWarning.setCheckable(False)
        self.actionSetLogWarning.setObjectName(_fromUtf8("actionSetLogWarning"))
        self.actionSetLogDebug = QtGui.QAction(CiliaC)
        self.actionSetLogDebug.setCheckable(False)
        self.actionSetLogDebug.setObjectName(_fromUtf8("actionSetLogDebug"))
        self.actionReport_Anterior = QtGui.QAction(CiliaC)
        self.actionReport_Anterior.setCheckable(False)
        self.actionReport_Anterior.setChecked(False)
        self.actionReport_Anterior.setObjectName(_fromUtf8("actionReport_Anterior"))
        self.actionReport_Lateral = QtGui.QAction(CiliaC)
        self.actionReport_Lateral.setCheckable(False)
        self.actionReport_Lateral.setChecked(False)
        self.actionReport_Lateral.setObjectName(_fromUtf8("actionReport_Lateral"))
        self.actionReport_Both = QtGui.QAction(CiliaC)
        self.actionReport_Both.setObjectName(_fromUtf8("actionReport_Both"))
        self.actionSetPixel_Size = QtGui.QAction(CiliaC)
        self.actionSetPixel_Size.setObjectName(_fromUtf8("actionSetPixel_Size"))
        self.actionImageWindow = QtGui.QAction(CiliaC)
        self.actionImageWindow.setObjectName(_fromUtf8("actionImageWindow"))
        self.actionMeasureROI_Position = QtGui.QAction(CiliaC)
        self.actionMeasureROI_Position.setObjectName(_fromUtf8("actionMeasureROI_Position"))
        self.actionTrackThreshold_ROI = QtGui.QAction(CiliaC)
        self.actionTrackThreshold_ROI.setObjectName(_fromUtf8("actionTrackThreshold_ROI"))
        self.actionTrack_ISO_Add = QtGui.QAction(CiliaC)
        self.actionTrack_ISO_Add.setObjectName(_fromUtf8("actionTrack_ISO_Add"))
        self.actionTrack_ISO_Display = QtGui.QAction(CiliaC)
        self.actionTrack_ISO_Display.setObjectName(_fromUtf8("actionTrack_ISO_Display"))
        self.actionTrack_ISO_Scale = QtGui.QAction(CiliaC)
        self.actionTrack_ISO_Scale.setObjectName(_fromUtf8("actionTrack_ISO_Scale"))
        self.actionTrack_ISO_Threshold = QtGui.QAction(CiliaC)
        self.actionTrack_ISO_Threshold.setObjectName(_fromUtf8("actionTrack_ISO_Threshold"))
        self.actionTrack_Manual_Start = QtGui.QAction(CiliaC)
        self.actionTrack_Manual_Start.setObjectName(_fromUtf8("actionTrack_Manual_Start"))
        self.actionTrack_Manual_Stop = QtGui.QAction(CiliaC)
        self.actionTrack_Manual_Stop.setObjectName(_fromUtf8("actionTrack_Manual_Stop"))
        self.actionTrack_Manual_Plot = QtGui.QAction(CiliaC)
        self.actionTrack_Manual_Plot.setObjectName(_fromUtf8("actionTrack_Manual_Plot"))
        self.actionTrack_Manual_Calc_Velocity = QtGui.QAction(CiliaC)
        self.actionTrack_Manual_Calc_Velocity.setObjectName(_fromUtf8("actionTrack_Manual_Calc_Velocity"))
        self.actionManual_Start = QtGui.QAction(CiliaC)
        self.actionManual_Start.setObjectName(_fromUtf8("actionManual_Start"))
        self.actionManual_Stop = QtGui.QAction(CiliaC)
        self.actionManual_Stop.setObjectName(_fromUtf8("actionManual_Stop"))
        self.actionManual_Clear = QtGui.QAction(CiliaC)
        self.actionManual_Clear.setObjectName(_fromUtf8("actionManual_Clear"))
        self.actionManual_Calc_Velocity = QtGui.QAction(CiliaC)
        self.actionManual_Calc_Velocity.setObjectName(_fromUtf8("actionManual_Calc_Velocity"))
        self.actionManual_Plot = QtGui.QAction(CiliaC)
        self.actionManual_Plot.setObjectName(_fromUtf8("actionManual_Plot"))
        self.actionManual_COM = QtGui.QAction(CiliaC)
        self.actionManual_COM.setCheckable(True)
        self.actionManual_COM.setChecked(True)
        self.actionManual_COM.setObjectName(_fromUtf8("actionManual_COM"))
        self.actionManual_Spiral = QtGui.QAction(CiliaC)
        self.actionManual_Spiral.setCheckable(True)
        self.actionManual_Spiral.setObjectName(_fromUtf8("actionManual_Spiral"))
        self.actionTrackNoROI_Active = QtGui.QAction(CiliaC)
        self.actionTrackNoROI_Active.setCheckable(True)
        self.actionTrackNoROI_Active.setObjectName(_fromUtf8("actionTrackNoROI_Active"))
        self.actionTrackFixedROI_Active = QtGui.QAction(CiliaC)
        self.actionTrackFixedROI_Active.setCheckable(True)
        self.actionTrackFixedROI_Active.setObjectName(_fromUtf8("actionTrackFixedROI_Active"))
        self.actionTrackMovingROI_Active = QtGui.QAction(CiliaC)
        self.actionTrackMovingROI_Active.setCheckable(True)
        self.actionTrackMovingROI_Active.setObjectName(_fromUtf8("actionTrackMovingROI_Active"))
        self.actionTrackMovement_Active = QtGui.QAction(CiliaC)
        self.actionTrackMovement_Active.setCheckable(True)
        self.actionTrackMovement_Active.setObjectName(_fromUtf8("actionTrackMovement_Active"))
        self.actionTrackSpiral_Active = QtGui.QAction(CiliaC)
        self.actionTrackSpiral_Active.setCheckable(True)
        self.actionTrackSpiral_Active.setObjectName(_fromUtf8("actionTrackSpiral_Active"))
        self.actionTrackNoROI_Calc_COM = QtGui.QAction(CiliaC)
        self.actionTrackNoROI_Calc_COM.setObjectName(_fromUtf8("actionTrackNoROI_Calc_COM"))
        self.actionTrackNoROI_Remove_COM = QtGui.QAction(CiliaC)
        self.actionTrackNoROI_Remove_COM.setObjectName(_fromUtf8("actionTrackNoROI_Remove_COM"))
        self.actionTrackFixedROI_Add_ROI = QtGui.QAction(CiliaC)
        self.actionTrackFixedROI_Add_ROI.setObjectName(_fromUtf8("actionTrackFixedROI_Add_ROI"))
        self.actionTrackFixedROI_Calc_COM = QtGui.QAction(CiliaC)
        self.actionTrackFixedROI_Calc_COM.setObjectName(_fromUtf8("actionTrackFixedROI_Calc_COM"))
        self.actionTrackFixedROI_Remove_ROI = QtGui.QAction(CiliaC)
        self.actionTrackFixedROI_Remove_ROI.setObjectName(_fromUtf8("actionTrackFixedROI_Remove_ROI"))
        self.actionTrackFixedROI_Remove_COM = QtGui.QAction(CiliaC)
        self.actionTrackFixedROI_Remove_COM.setObjectName(_fromUtf8("actionTrackFixedROI_Remove_COM"))
        self.actionTrackMovingROI_Add_ROI = QtGui.QAction(CiliaC)
        self.actionTrackMovingROI_Add_ROI.setObjectName(_fromUtf8("actionTrackMovingROI_Add_ROI"))
        self.actionTrackMovingROI_Calc_COM = QtGui.QAction(CiliaC)
        self.actionTrackMovingROI_Calc_COM.setObjectName(_fromUtf8("actionTrackMovingROI_Calc_COM"))
        self.actionTrackMovingROI_Remove_ROI = QtGui.QAction(CiliaC)
        self.actionTrackMovingROI_Remove_ROI.setObjectName(_fromUtf8("actionTrackMovingROI_Remove_ROI"))
        self.actionTrackMovingROI_Remove_COM = QtGui.QAction(CiliaC)
        self.actionTrackMovingROI_Remove_COM.setObjectName(_fromUtf8("actionTrackMovingROI_Remove_COM"))
        self.actionTrackMovement_Start = QtGui.QAction(CiliaC)
        self.actionTrackMovement_Start.setObjectName(_fromUtf8("actionTrackMovement_Start"))
        self.actionTrackMovement_Stop = QtGui.QAction(CiliaC)
        self.actionTrackMovement_Stop.setObjectName(_fromUtf8("actionTrackMovement_Stop"))
        self.actionTrackMovement_Remove_Current = QtGui.QAction(CiliaC)
        self.actionTrackMovement_Remove_Current.setObjectName(_fromUtf8("actionTrackMovement_Remove_Current"))
        self.actionTrackMovement_Remove_All = QtGui.QAction(CiliaC)
        self.actionTrackMovement_Remove_All.setObjectName(_fromUtf8("actionTrackMovement_Remove_All"))
        self.actionTrackSpiral_Start = QtGui.QAction(CiliaC)
        self.actionTrackSpiral_Start.setObjectName(_fromUtf8("actionTrackSpiral_Start"))
        self.actionTrackSpiral_Stop = QtGui.QAction(CiliaC)
        self.actionTrackSpiral_Stop.setObjectName(_fromUtf8("actionTrackSpiral_Stop"))
        self.actionTrackSpiral_Remove_Current = QtGui.QAction(CiliaC)
        self.actionTrackSpiral_Remove_Current.setObjectName(_fromUtf8("actionTrackSpiral_Remove_Current"))
        self.actionTrackSpiral_Remove_All = QtGui.QAction(CiliaC)
        self.actionTrackSpiral_Remove_All.setObjectName(_fromUtf8("actionTrackSpiral_Remove_All"))
        self.actionView_No_ROI = QtGui.QAction(CiliaC)
        self.actionView_No_ROI.setCheckable(True)
        self.actionView_No_ROI.setObjectName(_fromUtf8("actionView_No_ROI"))
        self.actionView_Fixed_ROI = QtGui.QAction(CiliaC)
        self.actionView_Fixed_ROI.setCheckable(True)
        self.actionView_Fixed_ROI.setObjectName(_fromUtf8("actionView_Fixed_ROI"))
        self.actionView_Moving_ROI = QtGui.QAction(CiliaC)
        self.actionView_Moving_ROI.setCheckable(True)
        self.actionView_Moving_ROI.setObjectName(_fromUtf8("actionView_Moving_ROI"))
        self.actionView_Movement = QtGui.QAction(CiliaC)
        self.actionView_Movement.setCheckable(True)
        self.actionView_Movement.setObjectName(_fromUtf8("actionView_Movement"))
        self.actionView_Spiral = QtGui.QAction(CiliaC)
        self.actionView_Spiral.setCheckable(True)
        self.actionView_Spiral.setObjectName(_fromUtf8("actionView_Spiral"))
        self.actionClose_Plots = QtGui.QAction(CiliaC)
        self.actionClose_Plots.setObjectName(_fromUtf8("actionClose_Plots"))
        self.actionSetReset_Zoom = QtGui.QAction(CiliaC)
        self.actionSetReset_Zoom.setObjectName(_fromUtf8("actionSetReset_Zoom"))
        self.menuCreate_Report.addAction(self.actionReport_Both)
        self.menuCreate_Report.addAction(self.actionReport_Anterior)
        self.menuCreate_Report.addAction(self.actionReport_Lateral)
        self.menu_File.addAction(self.actionLoad_Dicom_File)
        self.menu_File.addAction(self.actionSave_Dicom_File)
        self.menu_File.addAction(self.menuCreate_Report.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuRotate.addAction(self.actionRotate_Using_ROI)
        self.menuRotate.addAction(self.actionRotate_90_Deg_Left)
        self.menuRotate.addAction(self.actionRotate_90_Deg_Right)
        self.menuRotate.addAction(self.actionRotate_Set_Lateral_Angle)
        self.menu_Image.addAction(self.actionDICOM_Info)
        self.menu_Image.addAction(self.menuRotate.menuAction())
        self.menu_Image.addAction(self.actionSmooth)
        self.menu_Image.addAction(self.actionScale)
        self.menu_Image.addAction(self.actionReload_data)
        self.menu_Image.addAction(self.actionRemove_Background)
        self.menu_Image.addAction(self.actionMask_Frames)
        self.menu_Image.addAction(self.actionImageWindow)
        self.menuPrint.addAction(self.actionSummary)
        self.menuPrint.addAction(self.actionLateral_Movement)
        self.menuPrint.addAction(self.actionVirtical_Movement_2)
        self.menuPlot.addAction(self.action3D_Mesh)
        self.menuPlot.addAction(self.actionXYPlots)
        self.menuPlot.addAction(self.actionClose_Plots)
        self.menuPlot.addAction(self.menuPrint.menuAction())
        self.menuPlot.addAction(self.actionChange_Units)
        self.menuPlot.addAction(self.actionFit_Line)
        self.menuPlot.addAction(self.actionStraighten)
        self.menuPlot.addAction(self.actionExport)
        self.menuMeasure.addAction(self.actionVelocity_Limits)
        self.menuMeasure.addAction(self.actionCalcVelocity)
        self.menuMeasure.addAction(self.actionMeasure_Size_Inside_ROI)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.actionAnalyse_Calibration_Image)
        self.menuMeasure.addAction(self.actionMeasureROI_Position)
        self.menuMask.addAction(self.actionAdd_Mask)
        self.menuMask.addAction(self.actionApply_Mask)
        self.menuMask.addAction(self.actionRemove_Mask)
        self.menuISO.addAction(self.actionTrack_ISO_Add)
        self.menuISO.addAction(self.actionTrack_ISO_Display)
        self.menuISO.addAction(self.actionTrack_ISO_Scale)
        self.menuISO.addAction(self.actionTrack_ISO_Threshold)
        self.menuTrack_Movement.addAction(self.actionTrackMovement_Active)
        self.menuTrack_Movement.addAction(self.actionTrackMovement_Start)
        self.menuTrack_Movement.addAction(self.actionTrackMovement_Stop)
        self.menuTrack_Movement.addAction(self.actionTrackMovement_Remove_Current)
        self.menuTrack_Movement.addAction(self.actionTrackMovement_Remove_All)
        self.menuTrack_Spiral.addAction(self.actionTrackSpiral_Active)
        self.menuTrack_Spiral.addAction(self.actionTrackSpiral_Start)
        self.menuTrack_Spiral.addAction(self.actionTrackSpiral_Stop)
        self.menuTrack_Spiral.addAction(self.actionTrackSpiral_Remove_Current)
        self.menuTrack_Spiral.addAction(self.actionTrackSpiral_Remove_All)
        self.menuTrack_Manual.addAction(self.menuTrack_Movement.menuAction())
        self.menuTrack_Manual.addAction(self.menuTrack_Spiral.menuAction())
        self.menuTrack_No_ROI.addAction(self.actionTrackNoROI_Active)
        self.menuTrack_No_ROI.addAction(self.actionTrackNoROI_Calc_COM)
        self.menuTrack_No_ROI.addAction(self.actionTrackNoROI_Remove_COM)
        self.menuTrack_Fixed_ROI.addAction(self.actionTrackFixedROI_Active)
        self.menuTrack_Fixed_ROI.addAction(self.actionTrackFixedROI_Add_ROI)
        self.menuTrack_Fixed_ROI.addAction(self.actionTrackFixedROI_Calc_COM)
        self.menuTrack_Fixed_ROI.addAction(self.actionTrackFixedROI_Remove_ROI)
        self.menuTrack_Fixed_ROI.addAction(self.actionTrackFixedROI_Remove_COM)
        self.menuTrack_Moving_ROI.addAction(self.actionTrackMovingROI_Active)
        self.menuTrack_Moving_ROI.addAction(self.actionTrackMovingROI_Add_ROI)
        self.menuTrack_Moving_ROI.addAction(self.actionTrackMovingROI_Calc_COM)
        self.menuTrack_Moving_ROI.addAction(self.actionTrackMovingROI_Remove_ROI)
        self.menuTrack_Moving_ROI.addAction(self.actionTrackMovingROI_Remove_COM)
        self.menuTrack_Auto.addAction(self.menuTrack_No_ROI.menuAction())
        self.menuTrack_Auto.addAction(self.menuTrack_Fixed_ROI.menuAction())
        self.menuTrack_Auto.addAction(self.menuTrack_Moving_ROI.menuAction())
        self.menuTrack.addAction(self.menuTrack_Auto.menuAction())
        self.menuTrack.addAction(self.menuTrack_Manual.menuAction())
        self.menuTrack.addSeparator()
        self.menuTrack.addAction(self.actionAdd_ROI)
        self.menuTrack.addAction(self.actionDelete_ROI)
        self.menuTrack.addAction(self.actionReset_Limits)
        self.menuTrack.addSeparator()
        self.menuTrack.addSeparator()
        self.menuTrack.addAction(self.menuMask.menuAction())
        self.menuTrack.addAction(self.actionTrackThreshold_ROI)
        self.menuTrack.addAction(self.menuISO.menuAction())
        self.menuHelp.addAction(self.actionHelpAbout)
        self.menuTracking.addAction(self.actionTrackThreshold)
        self.menuTracking.addAction(self.actionTrackBins)
        self.menu3D_Plot.addAction(self.action3dZ_scale)
        self.menuLog_Level.addAction(self.actionSetLogInfo)
        self.menuLog_Level.addAction(self.actionSetLogWarning)
        self.menuLog_Level.addAction(self.actionSetLogDebug)
        self.menuSet.addAction(self.actionSet_Animation_Speed)
        self.menuSet.addAction(self.actionPlot_Size)
        self.menuSet.addAction(self.menuTracking.menuAction())
        self.menuSet.addAction(self.menu3D_Plot.menuAction())
        self.menuSet.addAction(self.actionSet_Summed_Sensitivity)
        self.menuSet.addAction(self.actionSet_Preprocess_image_on_Load)
        self.menuSet.addAction(self.menuLog_Level.menuAction())
        self.menuSet.addAction(self.actionSetPixel_Size)
        self.menuSet.addAction(self.actionSetReset_Zoom)
        self.menuManual.addSeparator()
        self.menuManual.addAction(self.actionManual_Start)
        self.menuManual.addAction(self.actionManual_Stop)
        self.menuManual.addAction(self.actionManual_Clear)
        self.menuManual.addSeparator()
        self.menuManual.addAction(self.actionManual_Calc_Velocity)
        self.menuManual.addAction(self.actionManual_Plot)
        self.menuView.addAction(self.actionView_No_ROI)
        self.menuView.addAction(self.actionView_Fixed_ROI)
        self.menuView.addAction(self.actionView_Moving_ROI)
        self.menuView.addAction(self.actionView_Movement)
        self.menuView.addAction(self.actionView_Spiral)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Image.menuAction())
        self.menubar.addAction(self.menuTrack.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuManual.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuMeasure.menuAction())
        self.menubar.addAction(self.menuSet.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CiliaC)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), CiliaC.close)
        QtCore.QObject.connect(self.buttonExit, QtCore.SIGNAL(_fromUtf8("clicked()")), CiliaC.close)
        QtCore.QMetaObject.connectSlotsByName(CiliaC)

    def retranslateUi(self, CiliaC):
        self.buttonRedraw.setToolTip(_translate("CiliaC", "Refresh Image", None))
        self.buttonRedraw.setText(_translate("CiliaC", "Redraw", None))
        self.buttonPrevImage.setToolTip(_translate("CiliaC", "Previous frame", None))
        self.buttonPrevImage.setText(_translate("CiliaC", "<", None))
        self.buttonNextImage.setToolTip(_translate("CiliaC", "Next Frame", None))
        self.buttonNextImage.setText(_translate("CiliaC", ">", None))
        self.buttonAnimateStart.setToolTip(_translate("CiliaC", "Start Animation", None))
        self.buttonAnimateStart.setText(_translate("CiliaC", "Animate", None))
        self.imageSlider.setToolTip(_translate("CiliaC", "Scroll Frames", None))
        self.buttonRotateLeft.setToolTip(_translate("CiliaC", "Rotate Left", None))
        self.buttonRotateLeft.setText(_translate("CiliaC", "RL", None))
        self.buttonRotateRight.setToolTip(_translate("CiliaC", "Rotate Right", None))
        self.buttonRotateRight.setText(_translate("CiliaC", "RR", None))
        self.buttonSmooth.setToolTip(_translate("CiliaC", "Apply Smoothing", None))
        self.buttonSmooth.setText(_translate("CiliaC", "...", None))
        self.buttonLoadFile.setToolTip(_translate("CiliaC", "Load Dataset", None))
        self.buttonLoadFile.setText(_translate("CiliaC", "...", None))
        self.buttonExit.setToolTip(_translate("CiliaC", "Exit", None))
        self.buttonExit.setText(_translate("CiliaC", "...", None))
        self.buttonCentreOfMass.setToolTip(_translate("CiliaC", "Calculate Centre of Mass", None))
        self.buttonCentreOfMass.setText(_translate("CiliaC", "Calc COM", None))
        self.buttonSummedImage.setToolTip(_translate("CiliaC", "Show summed image", None))
        self.buttonSummedImage.setText(_translate("CiliaC", "...", None))
        self.buttonRender.setToolTip(_translate("CiliaC", "Plot Image in 3D", None))
        self.buttonRender.setText(_translate("CiliaC", "...", None))
        self.buttonVHPlot.setToolTip(_translate("CiliaC", "Graph vertical and lateral movement", None))
        self.buttonVHPlot.setText(_translate("CiliaC", "plotVirtHor", None))
        self.groupBoxUnits.setTitle(_translate("CiliaC", "Units", None))
        self.radioButtonFrames.setToolTip(_translate("CiliaC", "Change units to Pixels and Frames", None))
        self.radioButtonFrames.setText(_translate("CiliaC", "pixels/frames", None))
        self.radioButtonTime.setToolTip(_translate("CiliaC", "Change units to mm and Seconds", None))
        self.radioButtonTime.setText(_translate("CiliaC", "mm/time", None))
        self.buttonShowOverlays.setToolTip(_translate("CiliaC", "Show Centre of Mass position", None))
        self.buttonShowOverlays.setText(_translate("CiliaC", "Show Overlays", None))
        self.spinFrom.setToolTip(_translate("CiliaC", "Start frame for COM", None))
        self.labelFrom.setText(_translate("CiliaC", "From", None))
        self.labelTo.setText(_translate("CiliaC", "To", None))
        self.spinTo.setToolTip(_translate("CiliaC", "End frame for COM", None))
        self.radioCOMFrame.setToolTip(_translate("CiliaC", "Measure COM using the whole frame", None))
        self.radioCOMFrame.setText(_translate("CiliaC", "Whole Frame", None))
        self.radioCOMInside.setToolTip(_translate("CiliaC", "Measure COM inside a fixed ROI", None))
        self.radioCOMInside.setText(_translate("CiliaC", "Inside ROI", None))
        self.radioCOMPeak.setToolTip(_translate("CiliaC", "Mesaure COM with a moving ROI", None))
        self.radioCOMPeak.setText(_translate("CiliaC", "Track Peak", None))
        self.label.setText(_translate("CiliaC", "Tracking", None))
        self.labelFrameNumber.setText(_translate("CiliaC", "0", None))
        self.buttonCalcVelocity.setText(_translate("CiliaC", "Calc Velocity", None))
        self.buttonProcessProceed.setToolTip(_translate("CiliaC", "Rotate Images", None))
        self.buttonProcessProceed.setText(_translate("CiliaC", "Proceed", None))
        self.buttonProcessCancel.setToolTip(_translate("CiliaC", "Rotate Images", None))
        self.buttonProcessCancel.setText(_translate("CiliaC", "Cancel", None))
        self.buttonSaveFile.setToolTip(_translate("CiliaC", "Save Dataset", None))
        self.buttonSaveFile.setText(_translate("CiliaC", "...", None))
        self.buttonSaveReport.setToolTip(_translate("CiliaC", "Save a report as PDF", None))
        self.buttonSaveReport.setText(_translate("CiliaC", "...", None))
        self.buttonSaveAsCSV.setToolTip(_translate("CiliaC", "Save a data as CSV", None))
        self.buttonSaveAsCSV.setText(_translate("CiliaC", "...", None))
        self.view1SliderMin.setToolTip(_translate("CiliaC", "Anterior Brightness Min", None))
        self.view1SliderMax.setToolTip(_translate("CiliaC", "Anterior Brightness Max", None))
        self.view2SliderMin.setToolTip(_translate("CiliaC", "Lateral Brightness Min", None))
        self.view2SliderMax.setToolTip(_translate("CiliaC", "Lateral Brightness Max", None))
        self.view1BCAutoLabel.setText(_translate("CiliaC", "Auto", None))
        self.view2BCAutoLabel.setText(_translate("CiliaC", "Auto", None))
        self.menu_File.setTitle(_translate("CiliaC", "&File", None))
        self.menuCreate_Report.setToolTip(_translate("CiliaC", "Create a PDF Summary", None))
        self.menuCreate_Report.setTitle(_translate("CiliaC", "Create Report", None))
        self.menu_Image.setTitle(_translate("CiliaC", "&Image", None))
        self.menuRotate.setTitle(_translate("CiliaC", "Rotate", None))
        self.menuPlot.setTitle(_translate("CiliaC", "Plot", None))
        self.menuPrint.setTitle(_translate("CiliaC", "Print", None))
        self.menuMeasure.setTitle(_translate("CiliaC", "Measure", None))
        self.menuTrack.setTitle(_translate("CiliaC", "Track", None))
        self.menuMask.setTitle(_translate("CiliaC", "Mask", None))
        self.menuISO.setTitle(_translate("CiliaC", "ISO", None))
        self.menuTrack_Manual.setTitle(_translate("CiliaC", "Manual", None))
        self.menuTrack_Movement.setTitle(_translate("CiliaC", "Movement", None))
        self.menuTrack_Spiral.setTitle(_translate("CiliaC", "Spiral", None))
        self.menuTrack_Auto.setTitle(_translate("CiliaC", "Auto", None))
        self.menuTrack_No_ROI.setTitle(_translate("CiliaC", "Whole Frame", None))
        self.menuTrack_Fixed_ROI.setTitle(_translate("CiliaC", "Fixed ROI", None))
        self.menuTrack_Moving_ROI.setTitle(_translate("CiliaC", "Moving ROI", None))
        self.menuHelp.setTitle(_translate("CiliaC", "Help", None))
        self.menuSet.setTitle(_translate("CiliaC", "Set", None))
        self.menuTracking.setTitle(_translate("CiliaC", "Tracking", None))
        self.menu3D_Plot.setTitle(_translate("CiliaC", "3D Plot", None))
        self.menuLog_Level.setTitle(_translate("CiliaC", "Log Level", None))
        self.menuManual.setTitle(_translate("CiliaC", "Manual", None))
        self.menuView.setTitle(_translate("CiliaC", "View", None))
        self.actionExit.setText(_translate("CiliaC", "Exit", None))
        self.actionDICOM_Info.setText(_translate("CiliaC", "DICOM Info", None))
        self.actionDICOM_Info.setToolTip(_translate("CiliaC", "Display DICOM Information", None))
        self.actionRotate_L.setText(_translate("CiliaC", "Rotate L", None))
        self.actionRotate_L.setToolTip(_translate("CiliaC", "Rotate Left", None))
        self.actionRotate_R.setText(_translate("CiliaC", "Rotate R", None))
        self.actionRotate_R.setToolTip(_translate("CiliaC", "Rotate Right", None))
        self.actionSmooth.setText(_translate("CiliaC", "Smooth", None))
        self.action3D_Mesh.setText(_translate("CiliaC", "3D Mesh", None))
        self.actionXYPlots.setText(_translate("CiliaC", "X and Y", None))
        self.actionInside_ROI.setText(_translate("CiliaC", "Inside ROI", None))
        self.actionROI_Peak.setText(_translate("CiliaC", "ROI Peak", None))
        self.actionScale.setText(_translate("CiliaC", "Scale", None))
        self.actionReload_data.setText(_translate("CiliaC", "Reload data", None))
        self.actionRemove_Background.setText(_translate("CiliaC", "Remove Background", None))
        self.actionChange_Units.setText(_translate("CiliaC", "Change Units", None))
        self.actionPrint_Virt.setText(_translate("CiliaC", "Print Virt", None))
        self.actionPrint_Horiz.setText(_translate("CiliaC", "Print Horiz", None))
        self.actionFit_Line.setText(_translate("CiliaC", "Fit Line", None))
        self.actionStraighten.setText(_translate("CiliaC", "Straighten", None))
        self.actionStraighten.setToolTip(_translate("CiliaC", "Straighten data", None))
        self.actionExport.setText(_translate("CiliaC", "Export", None))
        self.actionVelocity_Limits.setText(_translate("CiliaC", "Velocity Limits", None))
        self.actionCalcVelocity.setText(_translate("CiliaC", "Calculate Velocity", None))
        self.actionHelpAbout.setText(_translate("CiliaC", "About", None))
        self.actionMask_Frames.setText(_translate("CiliaC", "Mask Frames", None))
        self.actionAdd_Mask.setText(_translate("CiliaC", "Add Mask", None))
        self.actionApply_Mask.setText(_translate("CiliaC", "Apply Mask", None))
        self.actionRemove_Mask.setText(_translate("CiliaC", "Remove Mask", None))
        self.actionAdd_ROI.setText(_translate("CiliaC", "Add ROI", None))
        self.actionDelete_ROI.setText(_translate("CiliaC", "Delete ROI", None))
        self.actionEntire_Frame.setText(_translate("CiliaC", "Entire Frame", None))
        self.actionReset_Limits.setText(_translate("CiliaC", "Reset Limits", None))
        self.actionSummary.setText(_translate("CiliaC", "Summary", None))
        self.actionLateral_Movement.setText(_translate("CiliaC", "Lateral Movement", None))
        self.actionVirtical_Movement_2.setText(_translate("CiliaC", "Virtical Movement", None))
        self.actionPlot_Size.setText(_translate("CiliaC", "Plot Size", None))
        self.actionSet_Animation_Speed.setText(_translate("CiliaC", "Animation Speed", None))
        self.actionAnalyse_Calibration_Image.setText(_translate("CiliaC", "Analyse Calibration Image", None))
        self.actionTrackThreshold.setText(_translate("CiliaC", "Threshold", None))
        self.actionTrackBins.setText(_translate("CiliaC", "Bins", None))
        self.action3dZ_scale.setText(_translate("CiliaC", "Z scale", None))
        self.actionLoad_Dicom_File.setText(_translate("CiliaC", "Load Dicom File", None))
        self.actionSave_Dicom_File.setText(_translate("CiliaC", "Save Dicom File", None))
        self.actionRotate_Lat.setText(_translate("CiliaC", "Rotate Lat", None))
        self.actionRotate_Using_ROI.setText(_translate("CiliaC", "Using ROI", None))
        self.actionRotate_90_Deg_Left.setText(_translate("CiliaC", "90 Deg Left", None))
        self.actionRotate_90_Deg_Right.setText(_translate("CiliaC", "90 Deg Right", None))
        self.actionRotate_Set_Lateral_Angle.setText(_translate("CiliaC", "Set Lateral Angle", None))
        self.actionSet_Summed_Sensitivity.setText(_translate("CiliaC", "Summed Sensitivity", None))
        self.actionSet_Preprocess_image_on_Load.setText(_translate("CiliaC", "Preprocess image on Load", None))
        self.actionMeasure_Size_Inside_ROI.setText(_translate("CiliaC", "Size Inside ROI", None))
        self.actionSetLogInfo.setText(_translate("CiliaC", "Info", None))
        self.actionSetLogWarning.setText(_translate("CiliaC", "Warning", None))
        self.actionSetLogDebug.setText(_translate("CiliaC", "Debug", None))
        self.actionReport_Anterior.setText(_translate("CiliaC", "Anterior Only", None))
        self.actionReport_Lateral.setText(_translate("CiliaC", "Lateral Only", None))
        self.actionReport_Both.setText(_translate("CiliaC", "Both", None))
        self.actionSetPixel_Size.setText(_translate("CiliaC", "Pixel Size", None))
        self.actionImageWindow.setText(_translate("CiliaC", "Window", None))
        self.actionMeasureROI_Position.setText(_translate("CiliaC", "ROI Position", None))
        self.actionTrackThreshold_ROI.setText(_translate("CiliaC", "Isocurve ROI", None))
        self.actionTrack_ISO_Add.setText(_translate("CiliaC", "Add", None))
        self.actionTrack_ISO_Display.setText(_translate("CiliaC", "Display", None))
        self.actionTrack_ISO_Scale.setText(_translate("CiliaC", "Scale", None))
        self.actionTrack_ISO_Threshold.setText(_translate("CiliaC", "Threshold", None))
        self.actionTrack_Manual_Start.setText(_translate("CiliaC", "Start", None))
        self.actionTrack_Manual_Stop.setText(_translate("CiliaC", "Stop", None))
        self.actionTrack_Manual_Plot.setText(_translate("CiliaC", "Plot", None))
        self.actionTrack_Manual_Calc_Velocity.setText(_translate("CiliaC", "Calc Velocity", None))
        self.actionManual_Start.setText(_translate("CiliaC", "Start", None))
        self.actionManual_Stop.setText(_translate("CiliaC", "Stop", None))
        self.actionManual_Clear.setText(_translate("CiliaC", "Clear", None))
        self.actionManual_Calc_Velocity.setText(_translate("CiliaC", "Calc Velocity", None))
        self.actionManual_Plot.setText(_translate("CiliaC", "Plot", None))
        self.actionManual_COM.setText(_translate("CiliaC", "COM", None))
        self.actionManual_Spiral.setText(_translate("CiliaC", "Spiral", None))
        self.actionTrackNoROI_Active.setText(_translate("CiliaC", "Active", None))
        self.actionTrackFixedROI_Active.setText(_translate("CiliaC", "Active", None))
        self.actionTrackMovingROI_Active.setText(_translate("CiliaC", "Active", None))
        self.actionTrackMovement_Active.setText(_translate("CiliaC", "Active", None))
        self.actionTrackSpiral_Active.setText(_translate("CiliaC", "Active", None))
        self.actionTrackNoROI_Calc_COM.setText(_translate("CiliaC", "Calc COM", None))
        self.actionTrackNoROI_Remove_COM.setText(_translate("CiliaC", "Remove COM", None))
        self.actionTrackFixedROI_Add_ROI.setText(_translate("CiliaC", "Add ROI", None))
        self.actionTrackFixedROI_Calc_COM.setText(_translate("CiliaC", "Calc COM", None))
        self.actionTrackFixedROI_Remove_ROI.setText(_translate("CiliaC", "Remove ROI", None))
        self.actionTrackFixedROI_Remove_COM.setText(_translate("CiliaC", "Remove COM", None))
        self.actionTrackMovingROI_Add_ROI.setText(_translate("CiliaC", "Add ROI", None))
        self.actionTrackMovingROI_Calc_COM.setText(_translate("CiliaC", "Calc COM", None))
        self.actionTrackMovingROI_Remove_ROI.setText(_translate("CiliaC", "Remove ROI", None))
        self.actionTrackMovingROI_Remove_COM.setText(_translate("CiliaC", "Remove COM", None))
        self.actionTrackMovement_Start.setText(_translate("CiliaC", "Start", None))
        self.actionTrackMovement_Stop.setText(_translate("CiliaC", "Stop", None))
        self.actionTrackMovement_Remove_Current.setText(_translate("CiliaC", "Remove Current", None))
        self.actionTrackMovement_Remove_All.setText(_translate("CiliaC", "Remove All", None))
        self.actionTrackSpiral_Start.setText(_translate("CiliaC", "Start", None))
        self.actionTrackSpiral_Stop.setText(_translate("CiliaC", "Stop", None))
        self.actionTrackSpiral_Remove_Current.setText(_translate("CiliaC", "Remove Current", None))
        self.actionTrackSpiral_Remove_All.setText(_translate("CiliaC", "Remove All", None))
        self.actionView_No_ROI.setText(_translate("CiliaC", "Whole Frame", None))
        self.actionView_Fixed_ROI.setText(_translate("CiliaC", "Inside ROI", None))
        self.actionView_Moving_ROI.setText(_translate("CiliaC", "Track Peak", None))
        self.actionView_Movement.setText(_translate("CiliaC", "Movement", None))
        self.actionView_Spiral.setText(_translate("CiliaC", "Spiral", None))
        self.actionClose_Plots.setText(_translate("CiliaC", "Close Plots", None))
        self.actionSetReset_Zoom.setText(_translate("CiliaC", "Reset Zoom", None))

from pyqtgraph import GraphicsView
